// <auto-generated />
using System;
using CarbonAware.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarbonAware.Api.Migrations
{
    [DbContext(typeof(LoggingDbContext))]
    [Migration("20251114131017_AddWattTimeRequestId")]
    partial class AddWattTimeRequestId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarbonAware.Api.Data.AdviceCandidateLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("BestMoerAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<double?>("BestMoerUntilTarget")
                        .HasColumnType("float");

                    b.Property<string>("Cloud")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long>("ExecutionId")
                        .HasColumnType("bigint");

                    b.Property<double?>("MoerAtTarget")
                        .HasColumnType("float");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionId");

                    b.ToTable("AdviceCandidates");
                });

            modelBuilder.Entity("CarbonAware.Api.Data.AdviceExecutionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double?>("AverageEstimatedSavingPercent")
                        .HasColumnType("float");

                    b.Property<string>("BestWindowCloud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("BestWindowMoerGPerKwh")
                        .HasColumnType("float");

                    b.Property<string>("BestWindowRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("BestWindowWhen")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<double?>("EstimatedSavingGPerKwh")
                        .HasColumnType("float");

                    b.Property<double?>("EstimatedSavingPercent")
                        .HasColumnType("float");

                    b.Property<string>("HighestEmissionCloud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("HighestEmissionGPerKwh")
                        .HasColumnType("float");

                    b.Property<string>("HighestEmissionRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PreferredCloudsCsv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredRegionsCsv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SelectedCloud")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<double?>("SelectedMoerGPerKwh")
                        .HasColumnType("float");

                    b.Property<string>("SelectedRegion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("SelectedWhen")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("TargetWhen")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("AdviceExecutions");
                });

            modelBuilder.Entity("CarbonAware.Api.Data.WattTimeCallLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DurationMs")
                        .HasColumnType("int");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HorizonHours")
                        .HasColumnType("int");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Region")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequestUrl")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignalType")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("SourceFile")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("SourceLine")
                        .HasColumnType("int");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("WattTimeCalls");
                });

            modelBuilder.Entity("CarbonAware.Api.Data.AdviceCandidateLog", b =>
                {
                    b.HasOne("CarbonAware.Api.Data.AdviceExecutionLog", "Execution")
                        .WithMany("Candidates")
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Execution");
                });

            modelBuilder.Entity("CarbonAware.Api.Data.AdviceExecutionLog", b =>
                {
                    b.Navigation("Candidates");
                });
#pragma warning restore 612, 618
        }
    }
}
